// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXiaSTPBCz4B-Mjht8mkxy7uFM2C_GJLc',
    appId: '1:875582098148:web:db6629136ef6161b32baf1',
    messagingSenderId: '875582098148',
    projectId: 'whatsapp-clone-876bd',
    authDomain: 'whatsapp-clone-876bd.firebaseapp.com',
    storageBucket: 'whatsapp-clone-876bd.appspot.com',
    measurementId: 'G-899Y70BT53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxqmianmge_05vAH8bN2RUBxMb4IO_yD8',
    appId: '1:875582098148:android:310201ba53915a0232baf1',
    messagingSenderId: '875582098148',
    projectId: 'whatsapp-clone-876bd',
    storageBucket: 'whatsapp-clone-876bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6iC5Dpv1aJW6eL7aJnu9j-d8aIPOJc-w',
    appId: '1:875582098148:ios:9d8a3044ccfe2e2432baf1',
    messagingSenderId: '875582098148',
    projectId: 'whatsapp-clone-876bd',
    storageBucket: 'whatsapp-clone-876bd.appspot.com',
    iosClientId: '875582098148-tcnj7kucqv0fdi2o8nic7nad54vi6omb.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6iC5Dpv1aJW6eL7aJnu9j-d8aIPOJc-w',
    appId: '1:875582098148:ios:9d8a3044ccfe2e2432baf1',
    messagingSenderId: '875582098148',
    projectId: 'whatsapp-clone-876bd',
    storageBucket: 'whatsapp-clone-876bd.appspot.com',
    iosClientId: '875582098148-tcnj7kucqv0fdi2o8nic7nad54vi6omb.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
